### ISSUE TITLE
Program did not download new media

### ISSUE THREAD

**Issue by EEB9** [il90il90/TelegramAutoDownload#15]
Hello. I'm experiencing an issue with Telegram on my Windows 10 PC. I ran the program as an administrator and set its priority to 'Realtime' in the Task Manager. The program was running continuously for over 40 hours. However, when a new message arrived around the 40th hour, I noticed that the new media wasn't downloaded to the designated save folder.

I tried opening Telegram to trigger the download, but it still didn't work. Is there something I'm missing? Do I need to keep Telegram open for it to download media, or could there be another issue at play?

Any help or insights would be greatly appreciated!

**Comment by il90il90** [comment]
Hi EEB9,

You don't need to open the official Telegram desktop app to use `TelegramAutoDownload`.
Simply run the executable file, register with your Telegram account, and select the group or channel from which you want to download content.
The `TelegramAutoDownload` tool will automatically handle new content downloads as they come in.
